export const brutalistColors = {
  bg: '#EEEEE8',
  surface: '#FFFFFF',
  ink: '#1A1A1A',
  inkSoft: '#555555',
  muted: '#777777',
  mutedSoft: '#999999',
  rule: '#E0E0E0',
  hover: '#F5F5F0',
  rowHover: '#F7F7F2',
  badgeBg: '#F0F0EA',
  warningBg: '#FFFBEB',
  warningEdge: '#F5A623',
  successInk: '#276749',
  errorInk: '#C53030',
  blueAccent: '#1677FF',
  chartScale: ['#1A1A1A', '#555555', '#888888', '#AAAAAA', '#CCCCCC'],
  chartGrid: '#E0E0E0',
  chartAxisTick: '#888888',
};

export const monoFontStack = "'Space Mono', 'Courier New', monospace";

const antdTheme = {
  token: {
    colorPrimary: brutalistColors.ink,
    colorBgBase: brutalistColors.bg,
    colorBgContainer: brutalistColors.surface,
    colorBgLayout: brutalistColors.bg,
    colorBorder: brutalistColors.ink,
    colorBorderSecondary: brutalistColors.ink,
    borderRadius: 4,
    borderRadiusLG: 4,
    borderRadiusSM: 0,
    borderRadiusXS: 0,
    fontFamily: monoFontStack,
    fontFamilyCode: monoFontStack,
    fontSize: 13,
    colorText: brutalistColors.ink,
    colorTextHeading: brutalistColors.ink,
    colorTextSecondary: brutalistColors.inkSoft,
    colorTextTertiary: brutalistColors.muted,
    colorTextDescription: brutalistColors.muted,
    colorLink: brutalistColors.ink,
    colorInfo: brutalistColors.blueAccent,
    colorWarning: brutalistColors.warningEdge,
    colorSuccess: brutalistColors.successInk,
    colorError: brutalistColors.errorInk,
    controlHeight: 32,
    wireframe: false,
  },
  components: {
    Table: {
      headerBg: '#F5F5F0',
      headerColor: brutalistColors.ink,
      headerSortActiveBg: '#EBEBEB',
      headerSortHoverBg: '#EBEBEB',
      borderColor: brutalistColors.ink,
      rowHoverBg: brutalistColors.rowHover,
      fontFamily: monoFontStack,
      fontSize: 12,
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      headerSplitColor: brutalistColors.ink,
    },
    Button: {
      borderRadius: 0,
      borderRadiusLG: 0,
      borderRadiusSM: 0,
      fontFamily: monoFontStack,
      fontSize: 12,
      fontWeight: 700,
      controlHeight: 32,
      paddingInline: 16,
      defaultBg: brutalistColors.surface,
      defaultColor: brutalistColors.ink,
      defaultBorderColor: brutalistColors.ink,
      primaryShadow: 'none',
      defaultShadow: 'none',
    },
    Card: {
      borderRadius: 4,
      borderRadiusLG: 4,
      colorBorderSecondary: brutalistColors.ink,
      headerBg: brutalistColors.surface,
      headerFontSize: 13,
    },
    Tag: {
      borderRadiusSM: 0,
      fontFamily: monoFontStack,
      fontSize: 10,
    },
    Alert: {
      borderRadiusLG: 0,
      fontFamily: monoFontStack,
      colorWarningBg: brutalistColors.warningBg,
      colorWarningBorder: brutalistColors.warningEdge,
    },
    Tabs: {
      itemColor: brutalistColors.muted,
      itemSelectedColor: brutalistColors.blueAccent,
      itemHoverColor: brutalistColors.ink,
      inkBarColor: brutalistColors.blueAccent,
      titleFontSize: 13,
      fontFamily: monoFontStack,
    },
    Select: {
      borderRadius: 0,
      borderRadiusLG: 0,
      borderRadiusSM: 0,
      fontFamily: monoFontStack,
      fontSize: 12,
    },
    Pagination: {
      borderRadius: 0,
      itemActiveBg: brutalistColors.ink,
      colorPrimary: brutalistColors.surface,
      fontFamily: monoFontStack,
      fontSize: 12,
    },
    Progress: {
      defaultColor: brutalistColors.ink,
      remainingColor: brutalistColors.rule,
    },
    Statistic: {
      titleFontSize: 11,
      contentFontSize: 28,
      fontFamily: monoFontStack,
    },
    Empty: {
      fontFamily: monoFontStack,
    },
    Divider: {
      colorSplit: brutalistColors.ink,
    },
  },
};

export default antdTheme;
